### ISSUE TITLE
[0.0.1α ->0.1.0β] Task List 

### ISSUE THREAD

**Issue by kotoroshinoto** [kotoroshinoto/MinecraftModManager#8]
Minimal set of functions:
- [ ] Add ability to automatically install FML https://github.com/kotoroshinoto/MinecraftModManager/issues/13
- [ ] Add ability to automatically install any assistant loaders like liteloader, etc https://github.com/kotoroshinoto/MinecraftModManager/issues/14
- [ ] Tab with URLs for most common mods (don't auto-pull these unless author specifically allows it)
scan config directory for editable text files, add text editing window with navigable folder tree for easy config editing (maps, compasses, toomanyitems etc) https://github.com/kotoroshinoto/MinecraftModManager/issues/12
- [ ] support https for security reasons https://github.com/kotoroshinoto/MinecraftModManager/issues/11
- [ ] update client to requested version https://github.com/kotoroshinoto/MinecraftModManager/issues/5
- [ ] update server to requested version https://github.com/kotoroshinoto/MinecraftModManager/issues/9
- [ ] log in a user for purpose of playing online with client https://github.com/kotoroshinoto/MinecraftModManager/issues/4
- [ ] maintain user session (keepalive) https://github.com/kotoroshinoto/MinecraftModManager/issues/4
- [ ] update launcher,handler, etc so that the app handles different MC versions appropriately. https://github.com/kotoroshinoto/MinecraftModManager/issues/10
